platform :ios, '8.0'
use_frameworks!

xcodeproj '/users/ivangutnik/Documents/pingTracer/pingTracer.xcodeproj'

target "pingTracer" do
pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
pod 'GBPing', '~> 1.3'
pod 'Charts', '~> 2.1'




end
